version: '3'
services:
  nginx:
    container_name: "pp-nginx"
    image: "nginx"
    volumes:
      - ./../:/var/www/pp:cached
      - ./logs/nginx:/var/log/nginx
      - ../nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    environment:
      - TZ=Europe/Moscow

  mysql:
    container_name: "pp-mysql"
    image: "mysql:5.7"
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
      - ../mysql:/var/mysql-dump
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - TZ=Europe/Moscow

  php:
    container_name: "pp-php"
    build: ./php
    volumes:
      - ./../:/var/www/pp:cached
    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.internal remote_enable=1
      - PHP_IDE_CONFIG=serverName=Docker
      - TZ=Europe/Moscow
